name = "vybe-interview"
type = "javascript"
account_id = "f6079b48536414d3f838166e38f55d52"
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "vybe-interview-production"
workers_dev = false
route = "<YOUR_PRODUCTION_ROUTE>"
zone_id = "01b2db42c2e3898c83357cc587480fe9"

# Add the entry-point script
main = "workers/vybe-api/src/index.ts" 