#:schema node_modules/wrangler/config-schema.json
name = "vybe-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Bind variables
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "vybe-api"
workers_dev = true

# Cache configuration
[cache]
browser_TTL = 3600
edge_TTL = 3600

# Enable smart placement for optimal performance
[placement]
mode = "smart"

# Enable logs for monitoring
[observability]
enabled = true
